config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => "/cable"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'orders#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  post 'vendors/import_csv'
  post 'customers/import_csv'
  post 'admin/hotels/import_csv'
  post 'admin/products/import_csv'
  post 'admin/categories/import_csv'
  post 'admin/inventories/import_csv'

  resources :search_results, only: :index
  resources :dynamic_messages, only: :show
  resources :dynamic_item_messages, only: :show
  resources :filter_notifications, only: :show
  resources :orders do
    collection do
      post  'update_assign_user'
      post  'update_order'
      get   'send_orders'
      post  'send_orders_to_vendors'
      get   'item_details'
    end
  end
  resources :products do
    collection do
      post  'change_picture'
    end
  end
  resources :inventories do
    collection do
      get   'add_item'
      get   'manage_by_hotel'
      get   'view_stocks'
      get   'show_brand'
      post  'create_item'
      post  'restock'
    end
  end

  resources :vendors do
    collection do
      get   'list'
      get   'add_item'
      get   'supplier'
      get   'products'
      get   'items'
    end
  end

  resources :order_entries do
    collection do
      post  'update_entry'
      post  'change_status'
      post  'change_status_on_checklist'
      get   'history'
      get   'attachment'
      post  'add_existing_item'
      get   'download_attachment'
      get   'list'
    end
  end

  resources :email_templates

  resources :chatroom_orders do
    resources :order_users
    resources :messages
    resources :dropfiles, only: :create
    get 'load_messages/', :to => 'chatroom_orders#load_messages', as: 'load_messages'

    resources :order_entries, only: :load_item_messages do
      get 'load_item_messages/', :to => 'chatroom_orders#load_item_messages', as: 'load_item_messages'
    end
    resources :order_entries, only: :index do
      resources :item_messages, only: [:create, :new]
    end
  end

  resources :orders do
    resources :products do
      resources :item_messages
    end
    get 'item_details/:id', :to => 'products#item_details', as: 'item_details'
    resources :messages
    get 'load_messages/:chatroom_id', :to => 'orders#load_messages', as: 'load_messages', on: :collection
    get 'cancel_msg_update/:id', :to => 'messages#cancel_msg_update', as: 'cancel_msg_update', on: :collection
  end

  resources :order_entries, only: :load_item_messages do
    get 'load_item_messages/', :to => 'orders#load_item_messages', as: 'load_item_messages'
  end


  namespace :admin do
    resources :notifications
    resources :users
    resources :users_brands
    resources :users_groups
    resources :customers
    resources :inventories
    resources :vendors do
      resources :vendor_reviews
    end
    resources :products
    resources :categories
    resources :addresses
    resources :groups
    resources :style_attributes
    resources :orders do
      get 'duplicate_order', :to => 'orders#duplicate_order', as: 'duplicate_order'
      get 'archive_order', :to => 'orders#archive_order', as: 'archive_order'
    end
    resources :archive_orders, only: [:index]
    resources :order_entries
    resources :order_users
    resources :order_branches
    resources :vendors_products
    resources :vendor_categories
    resources :default_templates
    resources :brands do
      resources :hotels, only: [:show]
    end
    resources :hotels do
      get 'compose_email', :to => 'hotels#compose_email', as: 'compose_email'
    end  
    
    root to: "dashboards#index" # <--- Root route
  end
  #API Simple
  namespace :api do
    namespace :simple do
      resources :users do
        get 'list', on: :collection
        get 'branch_users', on: :collection
        get 'login', on: :collection
        get 'forgot_password', on: :collection
      end
      resources :categories do
        get 'list', on: :collection
      end
      resources :addresses do
        get 'list', on: :collection
        get 'branches', on: :collection
      end
      resources :brands do
        get 'list', on: :collection
        get 'details', to: :display
      end
      resources :groups do
        get 'list', on: :collection
      end
      resources :inventories do
        get 'list', on: :collection
        get 'overall', on: :collection
      end
      resources :products do
        get 'list', on: :collection
        get 'get_item_list', on: :collection
        get 'get_products_category', on: :collection
        post 'create_item', on: :collection
        post 'update_product', on: :collection
      end
      resources :vendors do
        get 'list', on: :collection
        get 'get_vendors_products', on: :collection
        get 'get_category_vendors', on: :collection
      end
      resources :style_attributes do
        get 'list', on: :collection
      end
      resources :orders do
        get 'list', on: :collection
        get 'send_orders', on: :collection
        get 'show_entries', on: :collection
        get 'show_users', on: :collection
        get 'get_latest_order', on: :collection
        get 'show_branches', on: :collection
        post 'update_assign_user'
      end
      resources :order_entries do
        get 'list', on: :collection
        get 'vendor_email_list',  on: :collection
        get 'attachment_list',  on: :collection
        post 'destroy_attachment', on: :collection
      end
      resources :sessions do
      end
      resources :hotels do
      end
    end
  end
  get 'static_pages/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < ApplicationController
    before_action :set_address, only: [:edit, :update]

    def index
        @addresses = Address.all
    end

    def edit
    end 

    def update
        respond_to do |format|
            if @address.update_attributes(address_params)
                format.html { redirect_to admin_addresses_path }
            else
                format.html { render 'edit' }
            end
        end
    end

    def new
        @address = Address.new
    end

    def create
        @address = Address.new(address_params)

        respond_to do |format|
           if @address.save
                format.html { redirect_to admin_addresses_path }
            else
                format.html { render 'new' }
            end
        end
    end

    private

        def address_params
            params.require(:address).permit(:street, :street_2, :city, :state, :zip, :country)
        end

        def set_address
            @address = Address.find(params[:id])
        end


end

app/controllers/api/simple/addresses_controller.rb
module Api
  module Simple
    class AddressesController < ApplicationController
      before_action :set_address, only: [:show, :update]

      def list
        addresses = Address.all
        render json: addresses.map { |address| { id: address.id, state: address.state, city: address.city } }
      end

      def branches
        addresses = Address.where("id IN (SELECT billing_address FROM users WHERE id IN (SELECT user_id FROM users_brands WHERE brand_id = #{params[:brand_id]}))  OR id IN (SELECT shipping_address FROM users WHERE id IN (SELECT user_id FROM users_brands WHERE brand_id = #{params[:brand_id]}))")
        render json: addresses.map { |address| { id: address.id, state: address.state, city: address.city } }
      end

      def create
        @address = Address.new(addresses_params)
        if @address.save
          render json: @address
        else
          render nothing: true, status: :bad_request
        end
      end

      def update
        if @address.update_attributes(addresses_params)
          head :no_content
        else
          render json: { status: 'failed' }, status: :unprocessable_entity
        end
      end

      def show
        render json: @address
      end

      protected

      def set_address
        @address = Address.find(params[:id])
      end

      def addresses_params
        params[:address]
      end

    end
  end
end

app/views/admin/addresses/_form.html.erb
<br>
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-content">
        
        <% if @address.errors.any? %>
          <div class="alert alert-danger alert-dismissable">
              <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
              <ul style="margin-bottom: 0;">
                <% @address.errors.full_messages.each do |error_message| %>
                  <li>
                    <%= error_message if @address.errors.full_messages.first == error_message %> <br />
                  </li>
                <% end %>
              </ul>
              
          </div>
        <% end %>
        
        <%= form_for [:admin, @address], html: { class: "form-horizontal" } do |f| %>

          <div class="form-group">
              <label class="col-sm-2 control-label">Street</label>
              <div class="col-sm-10">
                <%= f.text_field :street, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <label class="col-sm-2 control-label">Street 2</label>
              <div class="col-sm-10">
                <%= f.text_field :street_2, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <label class="col-sm-2 control-label">City</label>
              <div class="col-sm-10">
                <%= f.text_field :city, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <label class="col-sm-2 control-label">State</label>
              <div class="col-sm-10">
                <%= f.text_field :state, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <label class="col-sm-2 control-label">Country</label>
              <div class="col-sm-10">
                <%= f.text_field :country, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <div class="col-sm-4 col-sm-offset-2">
                  <%= link_to 'Cancel', admin_addresses_path, class: "btn btn-white" %>
                  <%= button_tag(type: 'Submit', class: "btn btn-primary") do %>
                    Save changes
                  <% end %> 
              </div>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    $('.chosen-select').chosen({width: "100%"});
  })
</script>

app/views/admin/addresses/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Addresses</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
                <%= link_to 'Address List', admin_addresses_path %>
            </li>
            <li class="active">
                <strong><%= @address.full_address %></strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<%= render 'form' %>

app/views/admin/addresses/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Addresses</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
              <%= link_to 'Address List', admin_addresses_path %>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins" style="font-size: 13px;">
        <div class="ibox-title">
                    <h5></h5>
                    <div class="ibox-tools">
                        <%= link_to 'Create New Address', new_admin_address_path, class: "btn btn-primary btn-sm" %>
                    </div>
                </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-list dataTable">
              <thead>
                          <tr role="row">
                            <th>Id</th>
                            <th>Street</th>
                            <th>Street 2</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Country</th>
                            <th></th>
                        </thead>
                        <tbody>
                          <% @addresses.each do |address| %>
                            <tr>
                                <td><%= address.id %></td>
                                <td><%= address.street %></td>
                                <td><%= address.street_2 %></td>
                                <td><%= address.city %></td>
                                <td><%= address.state %></td>
                                <td><%= address.country %></td>
                                <td>
                                  <div class="btn-group">
                                        <%= link_to 'Edit', edit_admin_address_path(address), class: "btn btn-xs btn-white" %>
                                        <button class="btn btn-xs btn-danger" type="button">Delete</button>
                                    </div>
                                </td>
                            </tr>
                          <% end %>
                        </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $( document ).on('turbolinks:load', function() {
       if (! $('.dataTables-list').hasClass('initialized')) {
            $('.dataTables-list').not('.initialized').addClass('initialized').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]
            });
        }

    });
</script>

app/views/admin/addresses/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Addresses</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
                <%= link_to 'Address List', admin_addresses_path %>
            </li>
            <li class="active">
                <strong>Create New Address</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<%= render 'form' %>

app/views/admin/addresses/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
                t("administrate.actions.edit_resource", name: page.page_title),
        [:edit, namespace, page.resource],
        class: "button",
        ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
        </div>
        </header>

        <section class="main-content__body">
          <dl>
            <% page.attributes.each do |attribute| %>
                <dt class="attribute-label" id="<%= attribute.name %>">
                  <%= t(
                              "helpers.label.#{resource_name}.#{attribute.name}",
                              default: attribute.name.titleize,
                      ) %>
                </dt>

                <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
                ><%= render_field attribute %></dd>
            <% end %>

            <dt class="attribute-label" id="users">
              Users
            </dt>

            <dd class="attribute-data attribute-data--has-many">
              <% users = User.where("billing_address = '#{page.resource.id}' OR shipping_address = '#{page.resource.id}'") %>

              <% if users.present? %>
                  <table aria-labelledby="users">
                    <thead>
                    <tr>
                      <th class="cell-label cell-label--number cell-label--false" scope="col" role="columnheader" aria-sort="none"> User ID  </th>
                      <th class="cell-label cell-label--number cell-label--false" scope="col" role="columnheader" aria-sort="none"> Name  </th>
                      <th class="cell-label cell-label--number cell-label--false" scope="col" role="columnheader" aria-sort="none"> E-mail  </th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                    </tr>
                    </thead>

                    <tbody>
                    <% users.each do |user| %>
                        <tr class="js-table-row" tabindex="0" role="link" data-url="/admin/users/<%= user.id %>">
                          <td class="cell-data cell-data--number">
                            <a href="/admin/users/<%= user.id %>" class="action-show">

                              <%= user.id %>

                            </a>
                          </td>
                          <td class="cell-data cell-data--number">
                            <a href="/admin/users/<%= user.id %>" class="action-show">

                              <%= user.first_name + " " + user.last_name %>

                            </a>
                          </td>

                          <td class="cell-data cell-data--number">
                            <a href="/admin/users/<%= user.id %>" class="action-show">

                              <%= user.email %>

                            </a>
                          </td>

                          <td><a class="action-edit" href="/admin/users/<%= user.id %>/edit">Edit</a></td>

                          <td><a class="text-color-red" data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/admin/users/<%= user.id %>">Destroy</a></td>
                        </tr>
                    <% end %>
              <% else %>
                  <dd class="attribute-data attribute-data--has-many">
                    None
                  </dd>
              <% end %>
              </tbody>
              </table>
            </dd>
          </dl>
        </section>