config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => "/cable"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'orders#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  post 'vendors/import_csv'
  post 'customers/import_csv'
  post 'admin/hotels/import_csv'
  post 'admin/products/import_csv'
  post 'admin/categories/import_csv'
  post 'admin/inventories/import_csv'

  resources :search_results, only: :index
  resources :dynamic_messages, only: :show
  resources :dynamic_item_messages, only: :show
  resources :filter_notifications, only: :show
  resources :orders do
    collection do
      post  'update_assign_user'
      post  'update_order'
      get   'send_orders'
      post  'send_orders_to_vendors'
      get   'item_details'
    end
  end
  resources :products do
    collection do
      post  'change_picture'
    end
  end
  resources :inventories do
    collection do
      get   'add_item'
      get   'manage_by_hotel'
      get   'view_stocks'
      get   'show_brand'
      post  'create_item'
      post  'restock'
    end
  end

  resources :vendors do
    collection do
      get   'list'
      get   'add_item'
      get   'supplier'
      get   'products'
      get   'items'
    end
  end

  resources :order_entries do
    collection do
      post  'update_entry'
      post  'change_status'
      post  'change_status_on_checklist'
      get   'history'
      get   'attachment'
      post  'add_existing_item'
      get   'download_attachment'
      get   'list'
    end
  end

  resources :email_templates

  resources :chatroom_orders do
    resources :order_users
    resources :messages
    resources :dropfiles, only: :create
    get 'load_messages/', :to => 'chatroom_orders#load_messages', as: 'load_messages'

    resources :order_entries, only: :load_item_messages do
      get 'load_item_messages/', :to => 'chatroom_orders#load_item_messages', as: 'load_item_messages'
    end
    resources :order_entries, only: :index do
      resources :item_messages, only: [:create, :new]
    end
  end

  resources :orders do
    resources :products do
      resources :item_messages
    end
    get 'item_details/:id', :to => 'products#item_details', as: 'item_details'
    resources :messages
    get 'load_messages/:chatroom_id', :to => 'orders#load_messages', as: 'load_messages', on: :collection
    get 'cancel_msg_update/:id', :to => 'messages#cancel_msg_update', as: 'cancel_msg_update', on: :collection
  end

  resources :order_entries, only: :load_item_messages do
    get 'load_item_messages/', :to => 'orders#load_item_messages', as: 'load_item_messages'
  end


  namespace :admin do
    resources :notifications
    resources :users
    resources :users_brands
    resources :users_groups
    resources :customers
    resources :inventories
    resources :vendors do
      resources :vendor_reviews
    end
    resources :products
    resources :categories
    resources :addresses
    resources :groups
    resources :style_attributes
    resources :orders do
      get 'duplicate_order', :to => 'orders#duplicate_order', as: 'duplicate_order'
      get 'archive_order', :to => 'orders#archive_order', as: 'archive_order'
    end
    resources :archive_orders, only: [:index]
    resources :order_entries
    resources :order_users
    resources :order_branches
    resources :vendors_products
    resources :vendor_categories
    resources :default_templates
    resources :brands do
      resources :hotels, only: [:show]
    end
    resources :hotels do
      get 'compose_email', :to => 'hotels#compose_email', as: 'compose_email'
    end  
    
    root to: "dashboards#index" # <--- Root route
  end
  #API Simple
  namespace :api do
    namespace :simple do
      resources :users do
        get 'list', on: :collection
        get 'branch_users', on: :collection
        get 'login', on: :collection
        get 'forgot_password', on: :collection
      end
      resources :categories do
        get 'list', on: :collection
      end
      resources :addresses do
        get 'list', on: :collection
        get 'branches', on: :collection
      end
      resources :brands do
        get 'list', on: :collection
        get 'details', to: :display
      end
      resources :groups do
        get 'list', on: :collection
      end
      resources :inventories do
        get 'list', on: :collection
        get 'overall', on: :collection
      end
      resources :products do
        get 'list', on: :collection
        get 'get_item_list', on: :collection
        get 'get_products_category', on: :collection
        post 'create_item', on: :collection
        post 'update_product', on: :collection
      end
      resources :vendors do
        get 'list', on: :collection
        get 'get_vendors_products', on: :collection
        get 'get_category_vendors', on: :collection
      end
      resources :style_attributes do
        get 'list', on: :collection
      end
      resources :orders do
        get 'list', on: :collection
        get 'send_orders', on: :collection
        get 'show_entries', on: :collection
        get 'show_users', on: :collection
        get 'get_latest_order', on: :collection
        get 'show_branches', on: :collection
        post 'update_assign_user'
      end
      resources :order_entries do
        get 'list', on: :collection
        get 'vendor_email_list',  on: :collection
        get 'attachment_list',  on: :collection
        post 'destroy_attachment', on: :collection
      end
      resources :sessions do
      end
      resources :hotels do
      end
    end
  end
  get 'static_pages/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :set_order, only: [:edit, :update, :show]

    def index
        @orders = Order.all
    end

    def edit
    end 

    def update
        respond_to do |format|
            if @order.update_attributes(order_params)
                format.html { redirect_to admin_orders_path }
            else
                format.html { render 'edit' }
            end
        end
    end

    def new
        @order = Order.new
    end

    def show
    end

    def create
        @order = Order.new(order_params)

        respond_to do |format|
           if @order.save
                format.html { redirect_to admin_orders_path }
            else
                format.html { render 'new' }
            end
        end
    end

    def duplicate_order
        @order = Order.find(params[:order_id])
        
        respond_to do |format|
            if @order.amoeba_dup.save
                @order = Order.last
                format.js
            end
        end
    end

    def archive_order
        @order = Order.find(params[:order_id])
        
        respond_to do |format|
            if @order.update(order_status_id: 6)
                
                format.js
            end
        end
    end

    private

        def order_params
            params.require(:order).permit(:created_by, :order_status_id, :customer_id, :delivery_address, :payment_address,
                                        :total_cost, :total_tax, :total_discount, :margin, :last_updated_by,
                                        :promise_date, :notes, :fulfillment_date, :lead_time, :total_budget,
                                        :urgent, :brand_id)
        end

        def set_order
            @order = Order.find(params[:id])
        end

end

app/controllers/api/simple/orders_controller.rb
module Api
  module Simple
    class OrdersController < ApplicationController
      before_action :set_order, only: [:show, :update]

      def list
        @orders = Order.order("updated_at, created_by DESC")
        render json: @orders,methods: [:created_by_name, :customer_name, :last_updated_by_name, :created_date, :brand_name, :brand_branches]
      end

      def show
        render json: @order,methods: [:created_by_name, :customer_name, :last_updated_by_name, :created_date, :updated_date, :brand_name, :brand_branches, :art, :regional, :comms, :processor, :temp_brand, :art_users, :regional_users, :comms_users, :processor_users]
      end

      def get_latest_order
        @order = Order.all.order('updated_at, created_by DESC').first
        render json: @order,methods: [:created_by_name, :customer_name, :last_updated_by_name, :created_date, :updated_date, :brand_name, :brand_branches, :art, :regional, :comms, :processor, :temp_brand, :art_users, :regional_users, :comms_users, :processor_users]
      end

      def show_entries
        @order_entries = OrderEntry.where("order_id = '#{params[:order_id]}'")
        render json: @order_entries, methods: [:product_name, :category_name]
      end

      def show_branches
        order = Order.find(params[:order_id])
        @order_branches = OrderBranch.where(:order_id => order.id, :brand_id => order.brand_id)
        render json: @order_branches, methods: [:state_and_city]
      end

      def show_users
        @order_users = OrderUser.where("order_id = '#{params[:order_id]}'")
        render json: @order_users, methods: [:regional_name, :comms_name, :art_name, :processor_name]
      end

      def update_status_entry
        entry = OrderEntry.find(params[:entry_id].to_i)
        if entry.update_attributes(:status => params[:status])
          order = Order.find(params[:order_id].to_i)
          redirect_to admin_order_path(order)
        end
      end

      def send_orders
        @order = Order.find(params[:order_id].to_i)
        @vendor = Vendor.find( params[:vendor_id].to_i)
        @order_entries = OrderEntry.where(:order_id => @order.id, :vendor => @vendor.id)
        @user = User.where(:email => "notifications@burningmidnight.com").first
        if @vendor.email.present? && !@vendor.email.nil?
          OrderMailer.with(order: @order, vendor: @vendor, order_entries: @order_entries).send_order_entries.deliver_now
          flash[:notice] = "Order has sent successfully."
        else
          flash[:error] = "Vendor doesn't have an email!"
        end
        redirect_to admin_order_path(@order)
      end

      def update
        temp_order = params[:order]
        order = Order.new
        order.brand_id = params[:temp_brand][:id]
        order.lead_time = temp_order[:lead_time]
        order.status = temp_order[:status]
        order.total_budget = temp_order[:total_budget]
        order.urgent = temp_order[:urget]

        if @order.update_attributes(:brand_id => order.brand_id, :lead_time => order.lead_time, :status => order.status, :total_budget => order.total_budget, :urgent => order.urgent)
          if params[:order_branch].present?
            OrderBranch.where(:order_id => @order.id).destroy_all
            temp_order_branch = params[:order_branch]
            temp_order_branch.each do |ob|
              order_branch = OrderBranch.new
              order_branch.brand_id = order.brand_id
              order_branch.order_id = order.id
              order_branch.address_id = ob
              order_branch.save
            end
          end
          if params[:art].present? || params[:comms].present? || params[:processor].present? || params[:regional].present?
            user = OrderUser.where(:order_id => @order.id).first
            user.update_attributes(:art => params[:art][:id], :regional => params[:regional][:id], :processor => params[:processor][:id], :comms => params[:comms][:id])
          end
          render json: @order,methods: [:created_by_name, :customer_name, :last_updated_by_name, :created_date, :updated_date, :brand_name, :brand_branches, :art, :comms, :regional, :processor, :temp_brand]
        end
      end

      def create
        temp_order = params[:order]
        order = Order.new
        order.brand_id = params[:temp_brand][:id]
        order.lead_time = temp_order[:lead_time]
        order.status = temp_order[:status]
        order.total_budget = temp_order[:total_budget]
        order.urgent = temp_order[:urget]

        if order.save
          if params[:order_branch].present?
            temp_order_branch = params[:order_branch]
            temp_order_branch.each do |ob|
              order_branch = OrderBranch.new
              order_branch.brand_id = order.brand_id
              order_branch.order_id = order.id
              order_branch.address_id = ob
              order_branch.save
            end
          end
          regional = []
          comms = []
          art = []
          processor = []
          arr_count = []
          i = 0
          params[:regional].each do |user|
            if user[:selected].to_s == 'true'
              regional.push(user)
            end
          end

          params[:comms].each do |user|
            if user[:selected].to_s == 'true'
              comms.push(user)
            end
          end

          params[:art].each do |user|
            if user[:selected].to_s == 'true'
              art.push(user)
            end
          end

          params[:processor].each do |user|
            if user[:selected].to_s == 'true'
              processor.push(user)
            end
          end

          arr_count.push(regional.length)
          arr_count.push(comms.length)
          arr_count.push(art.length)
          arr_count.push(processor.length)

          while i < arr_count.max
            order_user = OrderUser.new
            order_user.order_id = order.id
            if regional[i].present?
              order_user.regional = regional[i][:id]
            end
            if comms[i].present?
              order_user.comms = comms[i][:id]
            end
            if art[i].present?
              order_user.art = art[i][:id]
            end
            if processor[i].present?
              order_user.processor = processor[i][:id]
            end
            order_user.save
            i = i + 1
          end

=begin
          if params[:order_user].present?
            i = 0
            #temp_order_user = params[:order_user]
            @temp_length = 1

            if temp_order_user[:art].length > 0
              @temp_length = temp_order_user[:art].length
            end

            while i < @temp_length
              order_user = OrderUser.new
              order_user.order_id = order.id
              if i == 0
                if temp_order_user[:comms].present?
                  order_user.comms = temp_order_user[:comms]
                end
                if temp_order_user[:processor].present?
                  order_user.processor = temp_order_user[:processor]
                end
                if temp_order_user[:regional].present?
                  order_user.regional = temp_order_user[:regional]
                end
                order_user.art = temp_order_user[:art][i]
              end
              if temp_order_user[:art][i].present?
                order_user.art = temp_order_user[:art][i]
              end
              order_user.save
              i = i+1;
            end
          end
=end

            render json: order,methods: [:created_by_name, :customer_name, :last_updated_by_name, :created_date, :updated_date, :brand_name, :brand_branches, :art, :comms, :regional, :processor, :temp_brand]
        end
      end

      def update_assign_user
        @order = Order.find(params[:order_id])
        regional = []
        comms = []
        art = []
        processor = []
        arr_count = []
        i = 0
        if @order.present?
          OrderUser.where(:order_id => @order.id).destroy_all
          params[:regional].each do |user|
            if user[:selected].to_s == 'true'
              regional.push(user)
            end
          end

          params[:comms].each do |user|
            if user[:selected].to_s == 'true'
              comms.push(user)
            end
          end

          params[:art].each do |user|
            if user[:selected].to_s == 'true'
              art.push(user)
            end
          end

          params[:processor].each do |user|
            if user[:selected].to_s == 'true'
              processor.push(user)
            end
          end

          arr_count.push(regional.length)
          arr_count.push(comms.length)
          arr_count.push(art.length)
          arr_count.push(processor.length)

          while i < arr_count.max
            order_user = OrderUser.new
            order_user.order_id = @order.id
            if regional[i].present?
              order_user.regional = regional[i][:id]
            end
            if comms[i].present?
              order_user.comms = comms[i][:id]
            end
            if art[i].present?
              order_user.art = art[i][:id]
            end
            if processor[i].present?
              order_user.processor = processor[i][:id]
            end
            order_user.save
            i = i + 1
          end


          render json: @order,methods: [:created_by_name, :customer_name, :last_updated_by_name, :created_date, :updated_date, :brand_name, :brand_branches, :art, :comms, :regional, :processor, :temp_brand]
        end
      end

      protected

      def set_order
        @order = Order.find(params[:id])
      end

      def orders_params
        params[:order]
      end
    end
  end
end

app/helpers/order_helper.rb
module OrderHelper

	def check_image_url entry 
		if entry.product.present?
			if entry.product.picture.url.present?
			   entry.product.picture.url(:original)
			else
			  nil
			end	
		else
			nil	
		end	
	end	
end

app/views/admin/orders/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <% if attribute.name.to_s == "created_by" || attribute.name.to_s == "last_updated_by" || attribute.name.to_s == "customer"%>
                    <% if attribute.data.present? && attribute.data != 0 && attribute.data != '0' %>
                        <% user = User.find(attribute.data)%>
                        <%= link_to "#{user.first_name + ' ' + user.last_name}", admin_user_path(user) %>
                    <% end %>
                <% elsif  attribute.name.to_s == "delivery_address" || attribute.name.to_s == "payment_address"%>
                    <% if attribute.data.present? && attribute.data != 0 && attribute.data != '0' %>
                        <% address = Address.find(attribute.data)%>
                        <%= link_to "#{address.state + ' - ' + address.city}", admin_address_path(address) %>
                    <% end %>
                <% elsif  attribute.name.to_s == "brand_id" || attribute.name.to_s == "brand"%>
                    <% if attribute.data.present? && attribute.data != 0 && attribute.data != '0' %>
                        <% brand = Brand.find(attribute.data)%>
                        <%= link_to brand.name, admin_brand_path(brand) %>
                    <% end %>
                <% else %>
                    <%= render_field attribute %>
                <% end %>
              </a>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/archive_order.js.erb
$('#order-<%= @order.id %>').remove();

app/views/admin/orders/duplicate_order.js.erb
$("#tbody_orders").prepend("<%= escape_javascript(render 'order', order: @order) %>");

app/views/admin/orders/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Orders</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
              <%= link_to 'Orders List', admin_orders_path %>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins" style="font-size: 13px;">
        <div class="ibox-title">
                    <h5></h5>
                    <div class="ibox-tools">
                        <%= link_to 'Create New Order', new_admin_order_path, class: "btn btn-primary btn-sm" %>
                    </div>
                </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-list dataTable">
              <thead>
                          <tr role="row">
                            <th>Id</th>
                            <th>Ticket No.</th>
                            <th>Status</th>
                            <th>Customer</th>
                            <th>Brand</th>
                            <th>Total Cost</th>
                            <th></th>
                        </thead>
                        <tbody>
                          <% @orders.each do |order| %>
                            <tr>
                                <td><%= order.id %></td>
                                <td><%= link_to "Order-#{order.id}", admin_order_path(order) %></td>
                                <td><%= order.order_status.present? ? order.order_status.name : '' %></td>
                                <td><%= order.customer.present? ? order.customer.name : '' %></td>
                                <td>
                                    <% if order.brand.present? %>
                                        <%= link_to order.brand.name, admin_brand_path(order.brand) %>
                                    <% else %>
                                        N/A
                                    <% end %>
                                </td>
                                <td><%= order.total_cost %></td>
                                <td>
                                  <div class="btn-group">
                                        <%= link_to 'Edit', edit_admin_order_path(order), class: "btn btn-xs btn-white" %>
                                    </div>
                                </td>
                            </tr>
                          <% end %>
                        </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $( document ).on('turbolinks:load', function() {
       if (! $('.dataTables-list').hasClass('initialized')) {
            $('.dataTables-list').not('.initialized').addClass('initialized').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]
            });
        }

    });
</script>

app/views/admin/orders/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Orders</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
                <%= link_to 'Orders List', admin_orders_path %>
            </li>
            <li class="active">
                <strong><%= "Order-#{@order.id}" %></strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">

            <div class="ibox product-detail">
                <div class="ibox-content">

                    <div class="row">
                        <div class="col-md-12">
                            <h2 class="product-main-price pull-right">
                                <%= number_to_currency(@order.total_cost, unit: '$', :precision => 2, :delimiter => ',') %><br>
                                <small class="text-muted">Total Cost</small> 
                            </h2>

                            <h2 class="font-bold m-b-xs text-warning">
                                <%= "Order-#{@order.id}" %>
                            </h2>
                            <small style="font-size: 11px;"><%= @order.created_at.strftime("%d-%b-%Y %I:%M%P") %></small>
                            <div>
                                <div class="btn-group">
                                    <%= link_to edit_admin_order_path(@order), class: "btn btn-primary btn-xs" do %>
                                        <i class="fa fa-pencil"></i> Edit Order
                                    <% end %>
                                    <%= link_to admin_orders_path, class: "btn btn-white btn-xs" do %>
                                        <i class="fa fa-bars"></i> Back to List
                                    <% end %>
                                </div>
                            </div>
                            <hr>

                            <h4>Order Details</h4>
                        </div>
                        <div class="col-md-6">
                            <dl class="dl-horizontal m-t-md small">
                                <dt>Delivery Address</dt>
                                <dd><%= !@order.delivery_address.nil? ? Address.find(@order.delivery_address).full_address : 'N/A' %></dd>

                                <dt>Brand</dt>
                                <dd>
                                    <% if @order.brand.present? %>        
                                        <%= link_to @order.brand.name, admin_brand_path(@order.brand) %>
                                    <% else %>
                                        N/A
                                    <% end %>
                                </dd>

                                <dt>Customer</dt>
                                <dd>
                                    <% if @order.customer.present? %>
                                        <%= link_to @order.customer.name, admin_customer_path(@order.customer) %>
                                    <% else %>
                                        N/A
                                    <% end %>
                                </dd>
                            </dl>

                            <hr>
                        </div>
                        <div class="col-md-6">
                            <dl class="dl-horizontal m-t-md small">
                                <dt>Payment Address</dt>
                                <dd><%= !@order.payment_address.nil? ? Address.find(@order.payment_address).full_address : 'N/A' %></dd>

                                <dt>Created By</dt>
                                <dd><%= @order.created_by.nil? ? 'N/A' : @order.created_by %></dd>

                                <dt>Notes</dt>
                                <dd><%= @order.notes.nil? ? 'N/A' : @order.notes %></dd>
                            </dl>

                            <hr>
                        </div>
                    </div>

                </div>
            </div>

             <div class="ibox">
                <div class="ibox-title text-info">
                    Items
                </div>
                <div class="ibox-content">
                    <div class="table-responsive" style="overflow: visible;">
                        <table class="table table-hover issue-tracker">
                            <tbody id="tbody_orders">
                                <% @order.order_entries.each do |oe| %> 
                                    <% if oe.present? %>
                                        <%= render '/admin/products/product', oe: oe %>
                                    <% end %>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>