config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => "/cable"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'orders#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  post 'vendors/import_csv'
  post 'customers/import_csv'
  post 'admin/hotels/import_csv'
  post 'admin/products/import_csv'
  post 'admin/categories/import_csv'
  post 'admin/inventories/import_csv'

  resources :search_results, only: :index
  resources :dynamic_messages, only: :show
  resources :dynamic_item_messages, only: :show
  resources :filter_notifications, only: :show
  resources :orders do
    collection do
      post  'update_assign_user'
      post  'update_order'
      get   'send_orders'
      post  'send_orders_to_vendors'
      get   'item_details'
    end
  end
  resources :products do
    collection do
      post  'change_picture'
    end
  end
  resources :inventories do
    collection do
      get   'add_item'
      get   'manage_by_hotel'
      get   'view_stocks'
      get   'show_brand'
      post  'create_item'
      post  'restock'
    end
  end

  resources :vendors do
    collection do
      get   'list'
      get   'add_item'
      get   'supplier'
      get   'products'
      get   'items'
    end
  end

  resources :order_entries do
    collection do
      post  'update_entry'
      post  'change_status'
      post  'change_status_on_checklist'
      get   'history'
      get   'attachment'
      post  'add_existing_item'
      get   'download_attachment'
      get   'list'
    end
  end

  resources :email_templates

  resources :chatroom_orders do
    resources :order_users
    resources :messages
    resources :dropfiles, only: :create
    get 'load_messages/', :to => 'chatroom_orders#load_messages', as: 'load_messages'

    resources :order_entries, only: :load_item_messages do
      get 'load_item_messages/', :to => 'chatroom_orders#load_item_messages', as: 'load_item_messages'
    end
    resources :order_entries, only: :index do
      resources :item_messages, only: [:create, :new]
    end
  end

  resources :orders do
    resources :products do
      resources :item_messages
    end
    get 'item_details/:id', :to => 'products#item_details', as: 'item_details'
    resources :messages
    get 'load_messages/:chatroom_id', :to => 'orders#load_messages', as: 'load_messages', on: :collection
    get 'cancel_msg_update/:id', :to => 'messages#cancel_msg_update', as: 'cancel_msg_update', on: :collection
  end

  resources :order_entries, only: :load_item_messages do
    get 'load_item_messages/', :to => 'orders#load_item_messages', as: 'load_item_messages'
  end


  namespace :admin do
    resources :notifications
    resources :users
    resources :users_brands
    resources :users_groups
    resources :customers
    resources :inventories
    resources :vendors do
      resources :vendor_reviews
    end
    resources :products
    resources :categories
    resources :addresses
    resources :groups
    resources :style_attributes
    resources :orders do
      get 'duplicate_order', :to => 'orders#duplicate_order', as: 'duplicate_order'
      get 'archive_order', :to => 'orders#archive_order', as: 'archive_order'
    end
    resources :archive_orders, only: [:index]
    resources :order_entries
    resources :order_users
    resources :order_branches
    resources :vendors_products
    resources :vendor_categories
    resources :default_templates
    resources :brands do
      resources :hotels, only: [:show]
    end
    resources :hotels do
      get 'compose_email', :to => 'hotels#compose_email', as: 'compose_email'
    end  
    
    root to: "dashboards#index" # <--- Root route
  end
  #API Simple
  namespace :api do
    namespace :simple do
      resources :users do
        get 'list', on: :collection
        get 'branch_users', on: :collection
        get 'login', on: :collection
        get 'forgot_password', on: :collection
      end
      resources :categories do
        get 'list', on: :collection
      end
      resources :addresses do
        get 'list', on: :collection
        get 'branches', on: :collection
      end
      resources :brands do
        get 'list', on: :collection
        get 'details', to: :display
      end
      resources :groups do
        get 'list', on: :collection
      end
      resources :inventories do
        get 'list', on: :collection
        get 'overall', on: :collection
      end
      resources :products do
        get 'list', on: :collection
        get 'get_item_list', on: :collection
        get 'get_products_category', on: :collection
        post 'create_item', on: :collection
        post 'update_product', on: :collection
      end
      resources :vendors do
        get 'list', on: :collection
        get 'get_vendors_products', on: :collection
        get 'get_category_vendors', on: :collection
      end
      resources :style_attributes do
        get 'list', on: :collection
      end
      resources :orders do
        get 'list', on: :collection
        get 'send_orders', on: :collection
        get 'show_entries', on: :collection
        get 'show_users', on: :collection
        get 'get_latest_order', on: :collection
        get 'show_branches', on: :collection
        post 'update_assign_user'
      end
      resources :order_entries do
        get 'list', on: :collection
        get 'vendor_email_list',  on: :collection
        get 'attachment_list',  on: :collection
        post 'destroy_attachment', on: :collection
      end
      resources :sessions do
      end
      resources :hotels do
      end
    end
  end
  get 'static_pages/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord

	audited
	
	belongs_to :brand
	belongs_to :address
	has_many :order_branches
	has_many :orders, through: :order_branches
	has_many :chatroom_orders, through: :order_branches
	has_many :products

	validates :name, :brand_id, presence: true
	validates :name, uniqueness: true

	before_destroy :check_for_associations

	scope :hotel_with_brands, -> { includes(:brand) }

	extend FriendlyId
  	friendly_id :name, use: [:slugged, :finders]

  	def should_generate_new_friendly_id?
		name_changed?
	end

	require 'csv'

  	def self.import(file)
  		spreadsheet= open_spreadsheet(file)
	    spreadsheet.default_sheet = spreadsheet.sheets[0]

	    headers = Hash.new
	    spreadsheet.row(1).each_with_index {|header,i|headers[header] = i}
	    ((spreadsheet.first_row + 1)..spreadsheet.last_row).each do |row|
	      
	    	name = spreadsheet.row(row)[headers['Hotel']]

	    	hotel = Hotel.new
	    	hotel.name = name

	    	brand = Brand.find_by_name(name)
	    	if !brand.present? && !name.nil?
	    		Brand.create(name: name)
        		hotel.brand_id = Brand.last.id
	    	elsif brand.present?
	    		hotel.brand_id = brand.id
	    	end

	    	hotel.save

	    end
    
    end
  

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      when ".xls" then Roo::Excel.new (file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  private

    def check_for_associations
      if order_branches.any? || orders.any?
        throw(:abort)
      end
    end

end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController
    before_action :set_hotel, only: [:edit, :update, :show, :destroy]

    def index
        @hotels = Hotel.hotel_with_brands
    end

    def new
        @hotel = Hotel.new
    end

    def create
        @hotel = Hotel.new(hotel_params)

        respond_to do |format|
           if @hotel.save
                format.html { redirect_to admin_hotels_path }
            else
                format.html { render 'new' }
            end
        end
    end

    def edit
    end

    def show
    end

    def update
        respond_to do |format|
            if @hotel.update_attributes(hotel_params)
                format.html { redirect_to admin_hotels_path }
            else
                format.html { render 'edit' }
            end
        end
    end

    def compose_email
        respond_to do |format|
            @hotel = Hotel.find(params[:hotel_id])
            format.js
        end
    end

    def import_csv
        Hotel.import(params[:file])
        redirect_to admin_hotels_path
    end

    def destroy
        @hotels = Hotel.hotel_with_brands
        if @hotel.destroy
            flash.now[:notice] = "Hotel #{@hotel.name} successfully deleted."
        else
            flash.now[:error] = "Cannot delete this hotel, associations still exist."
        end
        render action: :index
    end

    private

        def hotel_params
            params.require(:hotel).permit(:name, :brand_id, :shipping_address, :address_id, :email, :notes, :contact_number)
        end

        def set_hotel
            @hotel = Hotel.friendly.find(params[:id])
        end

end

app/controllers/api/simple/hotels_controller.rb
module Api
  module Simple
    class HotelsController < ApplicationController
      def index
        hotels = Hotel.where(:brand_id => params[:brand_id])
        render json: hotels
      end
    end
  end
end

app/views/admin/hotels/_compose_email.html.erb
<div class="modal inmodal in" id="modal-shows" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="mail-body">
                    <form class="form-horizontal" method="get">
                        <div class="form-group"><label class="col-sm-2 control-label">To:</label>
                            <div class="col-sm-10"><input type="text" class="form-control" value="<%= @hotel.email %>"></div>
                        </div>
                        <div class="form-group"><label class="col-sm-2 control-label">Subject:</label>
                            <div class="col-sm-10"><input type="text" class="form-control" value=""></div>
                        </div>
                    </form>
                </div>
                <div class="summernote"></div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send Email</button>
            </div>
        </div>
    </div>
</div>

app/views/admin/hotels/_form.html.erb
<br>
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-content">

        <% if @hotel.errors.any? %>
          <div class="alert alert-danger alert-dismissable">
              <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
              <ul style="margin-bottom: 0;">
                <% @hotel.errors.full_messages.each do |error_message| %>
                  <li>
                    <%= error_message if @hotel.errors.full_messages.first == error_message %> <br />
                  </li>
                <% end %>
              </ul>
              
          </div>
        <% end %>
        
        <%= form_for [:admin, @hotel], html: { class: "form-horizontal" } do |f| %>

          <div class="form-group">
              <label class="col-sm-2 control-label">Name</label>
              <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Brand</label>
            <div class="col-sm-10">
               <%= f.collection_select( :brand_id, Brand.all, :id, :name, {include_blank: true}, {id: "brand_selection", class: "chosen-select"})%>
            </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Shipping Address</label>
            <div class="col-sm-10">
               <%= f.collection_select( :shipping_address, Address.all, :id, :full_address, {include_blank: true}, {id: "shipping_address_selection", class: "chosen-select"})%>
            </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Address</label>
            <div class="col-sm-10">
               <%= f.collection_select( :address_id, Address.all, :id, :full_address, {include_blank: true}, {id: "address_selection", class: "chosen-select"})%>
            </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <label class="col-sm-2 control-label">Email</label>
              <div class="col-sm-10">
                <%= f.text_field :email, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <label class="col-sm-2 control-label">Contact Number</label>
              <div class="col-sm-10">
                <%= f.text_field :contact_number, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <label class="col-sm-2 control-label">Notes</label>
              <div class="col-sm-10">
                <%= f.text_field :notes, class: "form-control" %>
              </div>
          </div>
          <div class="hr-line-dashed"></div>

          <div class="form-group">
              <div class="col-sm-4 col-sm-offset-2">
                  <%= link_to 'Cancel', admin_brands_path, class: "btn btn-white" %>
                  <%= button_tag(type: 'Submit', class: "btn btn-primary") do %>
                    Save changes
                  <% end %> 
              </div>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    $('.chosen-select').chosen({width: "100%"});
  })
</script>

app/views/admin/hotels/_hotel.html.erb
<tr id="hotel-<%= hotel.id %>">
    <td class="issue-info" style="width: 20%;">
        <a href="#">
            <%= link_to hotel.name, admin_hotel_path(hotel), class: 'prime-link' %>
        </a>

        <small>
            Name
        </small>
    </td>
    <td class="issue-info" style="width: 20%;">
        <a href="#">
            <%= hotel.address.present? ? hotel.address.street : 'N/A' %>
        </a>
        <small>
            Address
        </small>
    </td>
    <td class="issue-info" style="width: 10%;">
        <a href="#">
            <%= hotel.email %>
        </a>
        <small>
            Email
        </small>
    </td>
    <td class="issue-info" style="width: 10%;">
        <a href="#">
            <%= hotel.contact_number %>
        </a>
        <small>
            Contact Number
        </small>
    </td>
</tr>

app/views/admin/hotels/compose_email.js.erb
$('#modal-shows').replaceWith('<%= j render partial: "compose_email" %>');
$('#modal-shows').modal('show');
$('.summernote').summernote({
	height: 300
});

app/views/admin/hotels/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Hotels</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
                <%= link_to 'Hotels List', admin_hotels_path %>
            </li>
            <li class="active">
                <strong><%= @hotel.name %></strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<%= render 'form' %>

app/views/admin/hotels/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Hotels</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
              <%= link_to 'Hotels List', admin_hotels_path %>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">

        <%= flash_messages %>

      <div class="ibox float-e-margins" style="font-size: 13px;">
        <div class="ibox-title">
                    <h5></h5>
                    <div class="ibox-tools">
                        <a data-toggle="dropdown" id="#upload-hotels" href="#" aria-expanded="false" class="btn btn-primary btn-sm"> Upload Hotels</a>
                        <ul id="upload-hotels" class="dropdown-menu dropdown-messages2" aria-labelledby="upload-hotels">
                            <%= form_tag admin_hotels_import_csv_path, multipart: true do %>
                                <div class="form-group">
                                  <label for="exampleFormControlFile1">Import Here:</label>
                                  <%= file_field_tag :file %>
                                  <br><br>
                                  <%= submit_tag 'Import File', class: "btn btn-primary btn-sm" %>
                                </div>
                            <% end %>
                        </ul>
                        <%= link_to 'Create New Hotel', new_admin_hotel_path, class: "btn btn-primary btn-sm" %>
                    </div>
                </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-list dataTable">
              <thead>
                          <tr role="row">
                            <th>Id</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Brand</th>
                            <th>Address</th>
                            <th></th>
                        </thead>
                        <tbody>
                          <% @hotels.each do |hotel| %>
                            <tr>
                                <td><%= hotel.id %></td>
                                <td><%= link_to hotel.name, admin_brand_hotel_path(hotel.brand, hotel) %></td>
                                <td><%= hotel.email %></td>
                                <td>
                                    <% if hotel.brand.present? %>
                                        <%= link_to hotel.brand.name, admin_brand_path(hotel.brand) %>
                                    <% else %>
                                        N/A
                                    <% end %>
                                </td>
                                <td><%= hotel.address.present? ? hotel.address.street : '' %></td>
                                <td>
                                  <div class="btn-group">
                                        <%= link_to 'Edit', edit_admin_hotel_path(hotel), class: "btn btn-xs btn-white" %>
                                        <%= link_to 'Delete', admin_hotel_path(hotel), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "btn btn-xs btn-danger" %>
                                    </div>
                                </td>
                            </tr>
                          <% end %>
                        </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $( document ).on('turbolinks:load', function() {
        if (! $('.dataTables-list').hasClass('initialized')) {
            $('.dataTables-list').not('.initialized').addClass('initialized').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]
            });
        }

        $(document).on('click', '#upload-hotels', function (e) {
          e.stopPropagation();
        });

    });
</script>

app/views/admin/hotels/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Hotels</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
                <%= link_to 'Hotels List', admin_hotels_path %>
            </li>
            <li class="active">
                <strong>Create New Hotel</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<%= render 'form' %>

app/views/admin/hotels/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Hotels</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to 'Dashboard', admin_root_path %>
            </li>
            <li>
                <%= link_to 'Hotels List', admin_hotels_path %>
            </li>
            <li>
                <%= link_to @hotel.brand.name, admin_brand_path(@hotel.brand_id) %>
            </li>
            <li class="active">
                <strong><%= @hotel.name %></strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
                <div class="col-lg-12">

                    <div class="ibox product-detail">
                        <div class="ibox-content">

                            <div class="row">
                                <div class="col-md-4">

                                    <h2 class="font-bold m-b-xs text-warning">
                                        <%= @hotel.name %>
                                    </h2>
                                    <small><%= link_to @hotel.brand.name, admin_brand_path(@hotel.brand_id) %></small><br>
                                    <small>
                                        <% if @hotel.email.present? %>
                                            <%= link_to @hotel.email, admin_hotel_compose_email_path(@hotel), class: "text-info", remote: true %>
                                        <% else %>
                                            N/A
                                        <% end %>
                                    </small><br>
                                    <hr>

                                    <h4>Hotel Details</h4>

                                    <dl class="dl-horizontal m-t-md small">
                                        <dt>Address</dt>
                                        <dd><%= @hotel.address.present? ? Address.find(@hotel.address_id).full_address : 'N/A' %></dd>

                                        <dt>Shipping Address</dt>
                                        <dd><%= @hotel.shipping_address.present? ? Address.find(@hotel.shipping_address).full_address : 'N/A' %></dd>

                                        <dt>Contact Number</dt>
                                        <dd><%= @hotel.contact_number.present? ? @hotel.contact_number : 'N/A' %></dd>

                                        <dt>Notes</dt>
                                        <dd><%= @hotel.notes %></dd>

                                    </dl>

                                    <hr>

                                    <div>
                                        <div class="btn-group">
                                            <%= link_to edit_admin_hotel_path(@hotel), class: "btn btn-primary btn-xs" do %>
                                                <i class="fa fa-pencil"></i> Edit Hotel
                                            <% end %>
                                            <%= link_to admin_hotels_path, class: "btn btn-white btn-xs" do %>
                                                <i class="fa fa-bars"></i> Back to List
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <div class="tabs-container">
                                        <div class="nav nav-tabs" role="tablist">
                                            <a class="nav-item nav-link active" data-toggle="tab" href="#tab-1"> Users</a>
                                        </div>
                                        <div class="tab-content">
                                            <div id="tab-1" class="tab-pane active">
                                                <div class="panel-body">
                                                    <h4 class="text-info">Brand Associated Users</h4>
                                                    <br>
                                                    <table class="table table-striped table-hover">
                                                        <tbody>
                                                            <% @hotel.brand.users_brands.each do |ub| %>
                                                                <tr>
                                                                    <td><%= ub.user.full_name %></td>
                                                                    <td><%= ub.user.email %></td>
                                                                    <td>
                                                                        <% if ub.main_contact == true %>
                                                                            <span class="label label-primary">Main Contact</span>
                                                                        <% end %>
                                                                    </td>
                                                                </tr>
                                                            <% end %>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="ibox-footer">
                            <span class="pull-right">
                                Created at - <i class="fa fa-clock-o"></i> <%= @hotel.created_at.strftime("%d-%b-%C %I:%M%P") %>
                            </span>
                            -
                        </div>
                    </div>

                    <div class="ibox">
                        <div class="ibox-title text-info">
                            Associated Orders
                        </div>
                        <div class="ibox-content">
                            <div class="table-responsive" style="overflow: visible;">
                                <table class="table table-hover issue-tracker">
                                    <tbody id="tbody_orders">
                                        <% @hotel.orders.each do |order| %>
                                            <% if order.present? %> 
                                                <%= render '/admin/orders/order', order: order %>
                                            <% end %>
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
</div>
<script type="text/javascript">
    $(function(){
        $('.chosen-select').chosen({width: "100%"});
    })
</script>